language: go
go:
  - 1.2

install:
  - go get -v ./...
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending
