language: go
go:
  - 1.2

install:
  - go get -v ./...
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending