language: go
go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

# allow internal package imports, necessary for forked repositories
go_import_path: github.com/onsi/ginkgo

install:
  - go build ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - GO111MODULE="on" go mod tidy
  - diff -u <(echo -n) <(git diff go.mod)
  - diff -u <(echo -n) <(git diff go.sum)
  - $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace && go vet
